### ISSUE TITLE
Dump values using CAN module MCP2515

### ISSUE THREAD

**Issue by stomko11** [jagheterfredrik/esphome-rego1000#10]
My rego1000 is v.3.9.0
I am using MCP2515 which is working, I can read values, but most of them make no sense. I was hoping to be able to dump the values and map it accordingly. Any way I can achieve it using regodump?
This is my config for rego1000 and CAN:
```
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

canbus:
  - platform: mcp2515
    can_id: 0
    id: can0
    cs_pin: GPIO5
    bit_rate: 125kbps
```

Thanks
